
Vagrant.configure("2") do |config|

 
  config.vm.box = "almalinux/8"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.56.2"
  
  config.vm.synced_folder ".", "/vagrant", disabled:true
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provider :libvirt do |libvirt|
    libvirt.qemu_use_session = false
    libvirt.memory = 2048
    libvirt.cpus = 2
  end
end
