
Vagrant.configure("2") do |config|

 
  config.vm.box = "almalinux/8"
  config.vm.hostname = "app01"
  config.vm.network "private_network", ip: "192.168.56.3"
  
  config.vm.network "forwarded_port", guest: 8080, host:8080

  config.vm.provision "shell", path: "provision.sh"

  config.vm.provider :libvirt do |libvirt|
    libvirt.qemu_use_session = false
    libvirt.memory = 2048
    libvirt.cpus = 2
  end
end
